version: '2'
services:
  docker-proxy:
    image: jwilder/nginx-proxy
    container_name: docker-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - service-tier
networks:
  service-tier:
